artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/Satya-bit/Chicken-fecal-dataset/raw/main/chicken_small_dataset.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifcats/data_ingestion