artifacts_root: artifacts

data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL: https://github.com/Satya-bit/Chicken-fecal-dataset/raw/main/chicken_small_dataset.zip
    local_data_file: artifacts/data_ingestion/data.zip
    unzip_dir: artifacts/data_ingestion

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5  # This is adding custom layers after the pretrained model is downloaded


prepare_callbacks:
  root_dir: artifacts/prepare_callbacks
  tensorboard_root_log_dir: artifacts/prepare_callbacks/tensorboard_log_dir
  checkpoint_model_filepath: artifacts/prepare_callbacks/checkpoint_dir/model.h5 #After training some epochs it will save the model and if you wish to retrain it eill start training from that checkpoijt itself



training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5  #This model will be used for prediction